package com.pal.dipesh.razorpay.payment.dto.request;

import com.pal.dipesh.razorpay.common.entity.Money;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;
import java.util.Map;

public record OrderCreateRequest(
        @NotNull(message = "Amount is required")
        Money amount,

        @Size(max = 100, message = "Receipt must be at most 100 characters")
        String receipt, // Order-id generated by merchant

        Map<String, Object> notes,

        LocalDateTime expiresAt,

        @Valid
        CustomerDetails customer
) {
        public record CustomerDetails(
                @Size(max = 200)
                String name,

                @Email(message = "Invalid email format")
                @Size(max = 200)
                String email,

                @Size(max = 20)
                String phone
        ){}
}