package com.pal.dipesh.razorpay.payment.dto.request;

import com.pal.dipesh.razorpay.common.entity.Money;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;
import java.util.Map;

public record OrderCreateRequest(
        @NotNull(message = "Amount is required")
        Money amount,

        @Size(max = 100, message = "Receipt must be at most 100 characters")
        String receipt, // Order-id generated by merchant

        Map<String, Object> notes,

        LocalDateTime expiresAt
) {
}